### ISSUE TITLE
Could not pass event CurrencyAddEvent to ChestShop v3.8.13 (java.lang.StackOverflowError)

### ISSUE THREAD

**Issue by L4BORG** [dmulloy2/ChestShop-3#10]
Exception: http://pastebin.com/NLm0yfRY

```
>ver
[09:43:15 INFO]: This server is running CraftBukkit version git-TacoSpigot-"65fd35f" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
[09:43:15 INFO]: You are running the latest version
```

```
>ver ChestShop
[09:43:40 INFO]: ChestShop version 3.8.13
[09:43:40 INFO]: A chest shop for economy plugins.

[09:43:40 INFO]: Author: Acrobot
```

(b#10 (22.9.2016 11:58:37) from ci.dmulloy2.net)

https://github.com/drtshock/Essentials/issues/855

I think it might be related to https://github.com/dmulloy2/ChestShop-3/issues/8

**Comment by L4BORG** [comment]
```
>ver Essentials
[09:46:41 INFO]: Essentials version 2.0.1-b434
[09:46:41 INFO]: Provides an essential, core set of commands for Bukkit.
[09:46:41 INFO]: Website: http://tiny.cc/EssentialsCommands
[09:46:41 INFO]: Authors: Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally, drtshock and vemacs
```

```
>ver Vault
[09:47:00 INFO]: Vault version 1.5.6-b49
[09:47:00 INFO]: Vault is a Permissions & Economy API to allow plugins to more easily hook into these systems without needing to hook each individual system themselves.
[09:47:00 INFO]: Website: http://dev.bukkit.org/server-mods/vault/
[09:47:00 INFO]: Authors: cereal, Sleaker and mung3r
```

**Comment by dmulloy2** [comment]
What steps create this issue? i.e. how can I reproduce this?

**Comment by L4BORG** [comment]
To be honest I don't know...

**Comment by L4BORG** [comment]
Here's another one:

```
[22:37:19] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ChestShop v3.8.13
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [patched.jar:git-TacoSpigot-"65fd35f"]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [patched.jar:git-TacoSpigot-"65fd35f"]
    at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [patched.jar:git-TacoSpigot-"65fd35f"]
    at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [patched.jar:git-TacoSpigot-"65fd35f"]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:763) [patched.jar:git-TacoSpigot-"65fd35f"]
    at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [patched.jar:git-TacoSpigot-"65fd35f"]
    at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [patched.jar:git-TacoSpigot-"65fd35f"]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"65fd35f"]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-TacoSpigot-"65fd35f"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-TacoSpigot-"65fd35f"]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-TacoSpigot-"65fd35f"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-TacoSpigot-"65fd35f"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"65fd35f"]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.StackOverflowError
    at java.lang.String.valueOf(String.java:2994) ~[?:1.8.0_102]
    at java.lang.StringBuilder.append(StringBuilder.java:131) ~[?:1.8.0_102]
    at org.yaml.snakeyaml.nodes.MappingNode.toString(MappingNode.java:83) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    at java.lang.String.valueOf(String.java:2994) ~[?:1.8.0_102]
    at java.lang.StringBuilder.append(StringBuilder.java:131) ~[?:1.8.0_102]
    at org.yaml.snakeyaml.nodes.MappingNode.toString(MappingNode.java:83) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    at java.lang.String.valueOf(String.java:2994) ~[?:1.8.0_102]
    at java.lang.StringBuilder.append(StringBuilder.java:131) ~[?:1.8.0_102]
    at org.yaml.snakeyaml.nodes.MappingNode.toString(MappingNode.java:83) ~[patched.jar:git-TacoSpigot-"65fd35f"]
...
lots of lines...
...
    at org.yaml.snakeyaml.nodes.MappingNode.toString(MappingNode.java:83) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    at java.lang.String.valueOf(String.java:2994) ~[?:1.8.0_102]
    at java.lang.StringBuilder.append(StringBuilder.java:131) ~[?:1.8.0_102]
    at org.yaml.snakeyaml.nodes.MappingNode.toString(MappingNode.java:83) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    at java.lang.String.valueOf(String.java:2994) ~[?:1.8.0_102]
    at java.lang.StringBuilder.append(StringBuilder.java:131) ~[?:1.8.0_102]
    at org.yaml.snakeyaml.nodes.MappingNode.toString(MappingNode.java:83) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    at java.lang.String.valueOf(String.java:2994) ~[?:1.8.0_102]
```

**Comment by L4BORG** [comment]
We're now testing custom build of Essentials and custom build of ChestShop (latest build + fixed https://github.com/dmulloy2/ChestShop-3/issues/11 ) and so far the issue seems to be fixed. Gotta do some more testing and I'll get back to this later.

**Comment by dmulloy2** [comment]
What exactly did you change?

**Comment by L4BORG** [comment]
Sorry for late reply, after some more testing and stuff, I don't think this was Essentials economy issue: https://github.com/L4BORG/ChestShop-3/commit/24eb1b1e1970e0222021cfd4a94c7865d5f53232

And http://pastebin.com/eRD8wUFM is the result of corrupted items.db file (tried printing and decoding that base64 and there were some strange outputs... ie skulls instead of books).
