### ISSUE TITLE
Residence Support

### ISSUE THREAD

**Issue by Oruss7** [dmulloy2/ChestShop-3#13]
Hello guys, 

Can you repair the residence plugin support please ?

This is the "reloaded" plugin (you can talk to the dev in spigot discussion page)
https://www.spigotmc.org/threads/residence-1-7-10-up-to-1-10-paid.88667/

And this is the error:

```
[17:40:33] [Server thread/ERROR]: Could not pass event ProtectionCheckEvent to ChestShop v3.8.14
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:404) [ChestShop.jar:?]
at com.Acrobot.ChestShop.Security.canAccess(Security.java:36) [ChestShop.jar:?]
at com.Acrobot.ChestShop.Security.canAccess(Security.java:31) [ChestShop.jar:?]
at com.Acrobot.ChestShop.Listeners.Block.BlockPlace.onChestPlace(BlockPlace.java:38) [ChestShop.jar:?]
at sun.reflect.GeneratedMethodAccessor491.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:146) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
at net.minecraft.server.v1_10_R1.ItemStack.placeItem(ItemStack.java:162) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:534) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:890) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NoClassDefFoundError: net/t00thpick1/residence/api/ResidenceAPI
at com.Acrobot.ChestShop.Plugins.ResidenceChestProtection.onProtectionCheck(ResidenceChestProtection.java:28) ~[?:?]
at sun.reflect.GeneratedMethodAccessor573.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
... 29 more
```

I use https://github.com/L4BORG/ChestShop-3/releases/tag/3.8.14 fork for information

Thanks

**Comment by dmulloy2** [comment]
Looks as though the 'reloaded' plugin doesn't use the same API. I'd imagine the entire integration would have to be rewritten.

**Comment by Oruss7** [comment]
Any news ??
